#!/bin/bash

set -e
tabs -2

if [[ "$1" == "-noclear" ]]; then
	shift
else
	clear
fi

printUsage() {
	println "Usage:"
	println "\t" "Terminal is cleared unless '-noclear' flag is provided"
	println "\t" "./godo [-noclear] [help]  " "\t\t" "Print usage"
	println "\t" "./godo [-noclear] clean   " "\t\t" "Clean Go caches"
	println "\t" "./godo [-noclear] tidy    " "\t\t" "Tidy Go mod"
	println "\t" "./godo [-noclear] format  " "\t\t" "Format all Go code"
	println "\t" "./godo [-noclear] test    " "\t\t" "tidy -> format -> test -> vet"
	println "\t" "./godo [-noclear] audit   " "\t\t" "clean -> tidy -> format -> test -> vet"
	println "\t" "./godo [-noclear] example1" "\t\t" "Runs example 1: Minimal app"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

godoClean() {
	println "go clean -cache -testcache"
	go clean -cache -testcache
}

godoTidy() {
	println "go mod tidy"
	go mod tidy
}

godoFormat() {
	println "go fmt ./..."
	go fmt ./...
}

godoTest() {
	println "go test ./... -timeout \"2s\""
	go test ./... -timeout "2s"
}

godoVet() {
	println "go vet ./..."
	go vet ./...
}

godoRun() {
	println "CGO_ENABLED=0 go run '$1/main.go'"
	CGO_ENABLED=0 go run "$1/main.go"
}

if [[ "$1" == "" || "$1" == "help" ]]; then
	printUsage
	exit 0
fi

if [[ "$1" == "clean" ]]; then
	godoClean
	exit 0
fi

if [[ "$1" == "tidy" ]]; then
	godoTidy
	exit 0
fi

if [[ "$1" == "format" ]]; then
	godoFormat
	exit 0
fi

if [[ "$1" == "test" ]]; then
	godoTidy
	godoFormat
	godoTest
	godoVet
	exit 0
fi

if [[ "$1" == "audit" ]]; then
	godoClean
	godoTidy
	godoFormat
	godoTest
	godoVet
	exit 0
fi

if [[ "$1" == example* ]]; then
	godoTidy
	godoFormat
	godoRun $1
	exit 0
fi

println "I don't understand the option '$1'."
printUsage
exit 1

