#!/bin/bash

set -e
tabs -2

if [[ "$1" == "--noclear" ]]; then
	shift
else
	clear
fi

printUsage() {
	println "Usage:"
	println "\t" "Navigate to /ui to do UI specific stuff."
	println ""
	println "\t" "Terminal is cleared unless '--noclear' flag is provided."
	println "\t" "./godo [--noclear] [help]    " "\t\t" "Print usage"
	println "\t" "./godo [--noclear] clean     " "\t\t" "Clean Go caches"
	println "\t" "./godo [--noclear] tidy      " "\t\t" "Tidy Go mod"
	println "\t" "./godo [--noclear] fmt       " "\t\t" "Format all Go code"
	println "\t" "./godo [--noclear] test      " "\t\t" "tidy -> format -> test -> vet"
	println "\t" "./godo [--noclear] audit     " "\t\t" "tidy -> format -> test -> vet"
	println "\t" "./godo [--noclear] cleanaudit" "\t\t" "clean -> tidy -> format -> test -> vet"
	println "\t" "./godo [--noclear] dev       " "\t\t" "Build UI & start the app in dev mode"
	println "\t" "./godo [--noclear] run       " "\t\t" "Starts the app in dev mode (when build not needed)"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

runCmd() {
	println "$1"
	$1
}

godoClean() {
	runCmd "go clean -cache -testcache"
}

godoTidy() {
	runCmd "go mod tidy"
}

godoFormat() {
	runCmd "go fmt ./..."
}

godoTest() {
	runCmd "go test ./... -timeout 2s"
}

godoVet() {
	runCmd "go vet ./..."
}

godoRun() {
	runCmd "go run ./main.go"
}

godoUiBuild() {
	runCmd "npm --prefix ./ui/ run build"
}

godoUiTest() {
	runCmd "npm --prefix ./ui/ run test"
}

godoUiBuildlessAudit() {
	runCmd "npm --prefix ./ui/ run buildlessaudit"
}

if [[ "$1" == "" || "$1" == "help" ]]; then
	printUsage
	exit 0
fi

if [[ "$1" == "clean" ]]; then
	godoClean
	exit 0
fi

if [[ "$1" == "tidy" ]]; then
	godoTidy
	exit 0
fi

if [[ "$1" == "fmt" ]]; then
	godoFormat
	exit 0
fi

if [[ "$1" == "test" ]]; then
	godoTidy
	godoFormat
	godoUiTest
	godoTest
	godoVet
	exit 0
fi

if [[ "$1" == "audit" ]]; then
	godoUiBuild
	godoTidy
	godoFormat
	godoUiTest
	godoTest
	godoVet
	godoUiBuildlessAudit
	exit 0
fi

if [[ "$1" == "cleanaudit" ]]; then
	godoUiBuild
	godoClean
	godoTidy
	godoFormat
	godoUiTest
	godoTest
	godoVet
	godoUiBuildlessAudit
	exit 0
fi

if [[ "$1" == "dev" ]]; then
	godoTidy
	godoFormat
	godoUiBuild
	godoRun
	exit 0
fi

if [[ "$1" == "run" ]]; then
	godoTidy
	godoFormat
	godoRun
	exit 0
fi

println "I don't understand the option '$1'."
printUsage
exit 1

