package sprintl

import (
	"strings"
)

// Note: Contents of findline.go were AI generated by
// Claude then simplified.

// NeedleInHaystack holds byte position information about
// a substring (needle) within a bigger string (haystack).
// It is returned by [FindNeedle] and [FindNeedles], and
// provides fields and functions about the substring
// itself and the line it is on.
type NeedleInHaystack struct {
	// Line index.
	LineIndex int

	// Byte index of the first character of the line.
	LineStart int

	// Byte index one past the last character of the line
	// (exclusive, not including '\n').
	LineEnd int

	// Byte index of the first character of the search term.
	Start int

	// Byte index one past the last character of the search
	// term (exclusive).
	End int

	// The needle these positions relate to.
	Needle string

	// The haystack containing the needle.
	Haystack string
}

// FindNeedle locates needle within haystack and returns a
// NeedleInHaystack. If no match is found then an empty
// NeedleInHaystack is returned.
func FindNeedle(
	haystack, needle string,
	startingAt int,
) NeedleInHaystack {
	start := strings.Index(haystack[startingAt:], needle)
	if start == -1 {
		return NeedleInHaystack{}
	}

	// Correct for substring of haystack used.
	start += startingAt
	end := start + len(needle)

	// Find start of line: scan backwards for the previous
	// '\n'. +1 because we want to exclude the linefeed.
	lineStart := strings.LastIndexByte(
		haystack[:start],
		'\n',
	) + 1

	if lineStart == -1 {
		lineStart = 0
	}

	// Find end of line: scan forwards for the next '\n'.
	lineEnd := strings.IndexByte(haystack[start:], '\n')

	if lineEnd == -1 {
		lineEnd = len(haystack)
	} else {
		// Correct for substring of haystack used.
		lineEnd += start
	}

	lineIdx := strings.Count(haystack[:start], "\n")

	return NeedleInHaystack{
		LineIndex: lineIdx,
		LineStart: lineStart,
		LineEnd:   lineEnd,
		Start:     start,
		End:       end,
		Needle:    needle,
		Haystack:  haystack,
	}
}

// FindNeedles locates instances of the needle within
// haystack and returns a NeedleInHaystack.
func FindNeedles(
	haystack, needle string,
	startingAt int,
) []NeedleInHaystack {
	var result []NeedleInHaystack
	nih := NeedleInHaystack{
		End: startingAt,
	}

	for {
		nih = FindNeedle(haystack, needle, nih.End)

		if nih == (NeedleInHaystack{}) {
			break
		}

		result = append(result, nih)
	}

	return result
}

// LineNum returns the line number, i.e. line index + 1.
func (nih NeedleInHaystack) LineNum() int {
	return nih.LineIndex + 1
}

// Line returns the line text.
func (nih NeedleInHaystack) Line() string {
	return nih.Haystack[nih.LineStart:nih.LineEnd]
}

// InlineStart returns the byte index of the needle
// relative to the start of its line.
func (nih NeedleInHaystack) InlineStart() int {
	return nih.Start - nih.LineStart
}

// InlineEnd returns the byte index of the needle
// relative to the start of its line.
func (nih NeedleInHaystack) InlineEnd() int {
	return nih.End - nih.LineStart
}

// Replace replaces the instance of the needle within the
// haystack with text and returns the new haystack. The
// object itself will not be modified.
func (nih NeedleInHaystack) Replace(text string) string {
	return strings.Replace(nih.Haystack, nih.Needle, text, 1)
}

// ReplaceFindNext does the same as
// [NeedleInHaystack.Replace] but returns the next instance
// of the needle within the new haystack.
func (nih NeedleInHaystack) ReplaceFindNext(
	text string,
) NeedleInHaystack {
	hay := strings.Replace(nih.Haystack, nih.Needle, text, 1)
	return FindNeedle(hay, nih.Needle, nih.End)
}
