package schema

import (
	"database/sql"

	"github.com/PaulioRandall/randalls-spellbook/pkg/sin"
)

// SqliteSchema is a Go representation of sqlite_schema
// within SQLite3. Alternative names for the table include
// sqlite_master, sqlite_temp_schema, and
// sqlite_temp_master.
//
// See https://sqlite.org/schematab.html
type SqliteSchema struct {
	// Type or 'type' is the type of entry, e.g. 'table',
	// 'view', 'trigger', etc.
	Type string

	// Name or 'name' is the name of the entity.
	Name string

	// TableName or 'tbl_name' is the table name associated
	// with the schema entry, e.g. if Type is 'table' then
	// this would be the same as Name, and if the type is
	// 'trigger' then it would be the table that fires the
	// trigger.
	TableName string

	// Rootpage or 'rootpage'. If you need to use this value
	// then you will have done sufficient reading of the
	// SQLite docs that will render any docs I write
	// irrelevant.
	Rootpage int

	// Sql or 'sql' is the normalised SQL statement that
	// would create the object if executed and the object did
	// not already exist (ignoring any errors that may arise
	// from some constraints). It includes alterations made
	// to the entity through ALTER statements etc. It will be
	// an empty string for entries that are auto generated by
	// some constraints.
	Sql string
}

var (
	// ErrQueryEntity occurs when querying the sqlite_schema
	// table.
	ErrQueryEntity = sin.Template(
		"Could not query sqlite_schema for entity '%s'",
	)

	// ErrScanningRows occurs when scanning rows returned
	// from a sqlite_schema select.
	ErrScanningRows = sin.Template(
		"Could not scan sqlite_schema row %d for entity '%s'",
	)

	// ErrEntityNotFound occurs when the requested entity
	// does not exist within the database's sqlite_schema
	// table.
	ErrEntityNotFound = sin.Template(
		"Entity not found '%s'",
	)
)

// QuerySqliteSchema queries for and returns metadata about
// the entity where sqlite_schema.name matches the passed
// entityName. If the entity does not exist then
// ErrEntityNotFound will be in the error chain.
func QuerySqliteSchema(
	db *sql.DB,
	entityName string,
) (SqliteSchema, error) {
	query := `
		SELECT
			type,
			name,
			tbl_name,
			rootpage,
			sql
		FROM
			sqlite_schema
		WHERE
			type = "table"
		AND
			name = ?
	`

	var zero SqliteSchema

	rows, e := db.Query(query, entityName)
	if e != nil {
		return zero, ErrQueryEntity.Fmt(entityName).Wrap(e)
	}
	defer rows.Close()

	if !rows.Next() {
		return zero, ErrEntityNotFound.Fmt(entityName)
	}

	var ss SqliteSchema
	e = rows.Scan(
		&ss.Type,
		&ss.Name,
		&ss.TableName,
		&ss.Rootpage,
		&ss.Sql,
	)

	if e != nil {
		return zero, ErrScanningRows.Fmt(0).Wrap(e)
	}

	return ss, rows.Err()
}
