#!/bin/bash

set -e
tabs -2

if [[ "$1" == "--noclear" ]]; then
	shift
else
	clear
fi

printUsage() {
	println "Usage:"
	println "\t" "Terminal is cleared unless '--noclear' flag is provided"
	println "\t" "./svdo [--noclear] [help]" "\t\t" "Print usage"
	println "\t" "./svdo [--noclear] clean " "\t\t" "Delete build files and caches"
	println "\t" "./svdo [--noclear] update" "\t\t" "Updates and installs dependencies"
	println "\t" "./svdo [--noclear] format" "\t\t" "Format all code"
	println "\t" "./svdo [--noclear] build " "\t\t" "format -> build"
	println "\t" "./svdo [--noclear] test  " "\t\t" "format -> test"
	println "\t" "./svdo [--noclear] audit " "\t\t" "clean -> format -> test"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

svdoClean() {
	println "TODO"
}

svdoUpdate() {
	println "./deno.exe install"
	./deno.exe install
}

svdoFormat() {
	println "./deno.exe fmt"
	./deno.exe fmt
}

svdoBuild() {
	println "./deno.exe "
	./deno.exe install
}

svdoTest() {
	println "./deno.exe test"
	./deno.exe test
}

svdoBuild() {
	println "TODO"
}

if [[ "$1" == "" || "$1" == "help" ]]; then
	printUsage
	exit 0
fi

if [[ "$1" == "clean" ]]; then
	svdoClean
	exit 0
fi

if [[ "$1" == "update" ]]; then
	svdoUpdate
	exit 0
fi

if [[ "$1" == "format" ]]; then
	svdoFormat
	exit 0
fi

if [[ "$1" == "build" ]]; then
	svdoFormat
	svdoBuild
	exit 0
fi

if [[ "$1" == "test" ]]; then
	svdoFormat
	svdoTest
	exit 0
fi

if [[ "$1" == "audit" ]]; then
	svdoClean
	svdoFormat
	svdoTest
	exit 0
fi

println "I don't understand the option '$1'."
printUsage
exit 1

